### ISSUE TITLE
Limited to Windows acc. to addons.mozilla.org?

### ISSUE THREAD

**Issue by darklajid** [traxium/tabtree#10]
Running Firefox Developer Edition on Linux. I see 

"Not available for your platform"

and if I do go ahead and install it anyway, it doesn't show up (i.e. no tab bar).
Is that classification correct? I was under the assumption, that this plugin is JS only / platform agnostic? If that isn't the case, do you plan to add support for other platforms (in this case, Linux)?

**Comment by traxium** [comment]
I'm going to add Linux support. And it'll be before the tree folding feature.
I also tried to run my add-on on Ubuntu. And It didn't work. And Browser Console didn't show any add-on related errors. So I decided to postpone Linux support until more urgent bugs are fixed. Sorry I am so slow but I just can't work faster.

**Comment by traxium** [comment]
Linux support added in 1.2.2. But I only tested it on Ubuntu 14.04 LTS (64-bit) and Mint 17.2 (32-bit). If you have issues on another Linux distros please let me know.

**Comment by traxium** [comment]
OS X support is added in version 1.4.2. If nobody has anything to say I'll close the issue.
