### ISSUE TITLE
Feature request: collapse a node in the tab tree, hiding its children

### ISSUE THREAD

**Issue by theres-waldo** [traxium/tabtree#128]
It would be really nice to be able to collapse a node in the tab tree, hiding its children. (Then it can be expanded again, showing the children again).

A similar addon, Tree Style Tabs, has this feature.

**Comment by sam113101** [comment]
Like this? #4

**Comment by theres-waldo** [comment]
Yes - thanks for the link. Closing as dupe of #4.
