### ISSUE TITLE
v1.2.2 breaks all chrome

### ISSUE THREAD

**Issue by CattiestPenny** [traxium/tabtree#13]
When the new version (1.2.2) was applied a few minutes ago, all browser chrome went blank (all toolbars and tab bar). Items can still be selected, but there is no way to know where they are. I restarted FF in safe mode and enabled addons one by one. Tab Tree seems to be the problem. I am using stable release v40.0.2 and dev edition v42.0a2. It is broken in both.
![blank ff chrome](https://cloud.githubusercontent.com/assets/14078225/9610949/65526554-50a2-11e5-956e-cfd9ffa34846.PNG)

**Comment by strigona-worksight** [comment]
See #12. Try restarting your browser or disable/enable the extension.

**Comment by CattiestPenny** [comment]
I just saw #12. Restarting browser and disable/enable extension did not work. I had to turn off hardware acceleration and now it seems to be working. Fingers crossed. Still not really a long-term solution.

**Comment by traxium** [comment]
Can you try the latest version 1.2.4? (already on AMO (addons.mozilla.org))

**Comment by CattiestPenny** [comment]
I tried v1.2.4 and still have the same issue (blank chrome ui when hardware acceleration = true). Chrome does not break right away once hardware acceleration is enabled, it breaks after restarting the browser. Here are my Tab Tree preferences if that helps:

![blank ff chrome](https://cloud.githubusercontent.com/assets/14078225/9616787/b5816f7a-50c5-11e5-90e4-2eb8b124450d.PNG)
![tabtree pref](https://cloud.githubusercontent.com/assets/14078225/9616788/b588dad0-50c5-11e5-9285-68e4e12f3c0c.PNG)

**Comment by traxium** [comment]
https://dl.dropboxusercontent.com/u/60847262/getCellProperties/TabsTree%40traxium.xpi
https://dl.dropboxusercontent.com/u/60847262/canDrop/TabsTree%40traxium.xpi
https://dl.dropboxusercontent.com/u/60847262/getCellProperties/TabsTree%40traxium.xpi
https://dl.dropboxusercontent.com/u/60847262/getCellcanDrop/TabsTree%40traxium.xpi

Please try this versions and tell what version doesn't have this bug. One of this 4 versions should work if v1.2.2 really worked on your system. In each link above I commented out the lines that could cause the bug. It'll help to narrow the problem.

**Comment by CattiestPenny** [comment]
I just got home and updated my Win10/FF 40.0.3 machine to the generally available v1.2.4 Tab Tree release. Everything is working as expected after trying to break it. I VPNed to my Win7 work computer, and now everything seems to be fine in the generally available v1.2.4 release as well. Not sure why it's working now, but all seems to be well.
