### ISSUE TITLE
[Bug] UI breaks with Firefox 47

### ISSUE THREAD

**Issue by TempSpas** [traxium/tabtree#136]
[As seen here.](http://i.imgur.com/SdrjfH9.png)

With the most recent update to Firefox 47, the URL bar now overlaps with the title bar and close/minimize buttons. I can fix this for the session by pressing the green button to expand the window to fullscreen and then unexpand it, but any time I restart Firefox the glitch will appear again.

**Comment by TempSpas** [comment]
This is on OS X 10.11.5.

**Comment by limejet** [comment]
[Also happens](http://i.imgur.com/eZ29neV.png) on Windows 10. Firefox 47.0 x64
