### ISSUE TITLE
[Feature] Persist Tree Width

### ISSUE THREAD

**Issue by strigona-worksight** [traxium/tabtree#14]
The default tree width is a little narrow for my liking so I widen it. Unfortunately the width doesn't persist when restarting or opening new windows so I'm forced to resize it frequently.

**Comment by traxium** [comment]
Tab Tree saved the tree width for every window when a window is being closed. And restored it when a window is being opened. The default value is 200px. So it should already have persisted the sidebar width unless Firefox crashed. When you disable Tab Tree in Add-ons Manager it deletes the saved width values.
In 469f8b5 the value is saved every time the sidebar width is changed.

**Comment by strigona-worksight** [comment]
Thanks! Restarting the browser now persists the width.

However, this appears to only work with the first window. Creating a new window results in the width being reset to 200px.

**Comment by traxium** [comment]
In 9a18a2a it should behave as you expect.

**Comment by strigona-worksight** [comment]
I'm still not having any luck with new windows. The new windows are resetting to the default 200px.

For what it's worth I'm on Firefox 41 (beta) 64bit, Windows 10 64bit.

**Comment by traxium** [comment]
I'm not sure you are using the latest 9a18a2a commit. I haven't uploaded it on AMO (addons.mozilla.org) yet.

**Comment by strigona-worksight** [comment]
Ah I see. I'll look into getting the build tools.

**Comment by strigona-worksight** [comment]
I didn't realize all I had to do was zip the project and rename to an XPI.. thought I had to build using JPM. Anyway, tested it and it looks good!

**Comment by traxium** [comment]
Actually It is not necessary to zip the project. You can replace .xpi file (in your profile folder) with the ordinary folder named after the add-on ID ("TabsTree@traxium" in this case, without ".xpi" at the end).

**Comment by strigona-worksight** [comment]
Ah I see, still I was expecting to have to use JPM to build it which is why I put it off as long as I did :)
