### ISSUE TITLE
[Bug] Interaction with DevEdition Theme Enabler bugged

### ISSUE THREAD

**Issue by TempSpas** [traxium/tabtree#149]
With the newest update to DevEdition Theme Enabler to allow it to be compatible with e10s, the option to "Try to mimic the Firefox theme" breaks and shows light tabs that turn black when hovered over.

Is the developer of this addon still actively working on this? None of the issues I've reported over the past few months have received any response, and I'm wondering if I should switch to a different Tree Tab extension.

**Comment by traxium** [comment]
Yes, I use my extension every day. I'm going to fix #136 next.
