### ISSUE TITLE
Duplicate tree in private browsing mode

### ISSUE THREAD

**Issue by vesatoivonen** [traxium/tabtree#15]
Opening a private browsing window from existing session sometimes opens two or tree tab trees.
I'm using Firefox 42.0a2 on Xubuntu 14.04 and Tab Tree 1.3.3.

**Comment by traxium** [comment]
Excess tab trees appear only in a new private window. And not in other windows. Am I correct?

**Comment by vesatoivonen** [comment]
You are correct.

**Comment by traxium** [comment]
It should be fixed in 1.3.5 (already available on AMO).

**Comment by vesatoivonen** [comment]
It surely seems like it. Thanks.
