### ISSUE TITLE
1.4.7 invisible on Linux

### ISSUE THREAD

**Issue by shabbyrobe** [traxium/tabtree#151]
The latest tabtree update doesn't work on Lubuntu 16.04. If I start a fresh Firefox profile and install Tab Tree, the pane never shows. F8 doesn't do anything either.

Reverting to a manually installed version of 1.4.6 has temporarily fixed my issue.

**Comment by Gotolei** [comment]
Also having this. Doesn't seem to be showing at all.

Fx48, no e10s, Xubuntu 16.04

**Comment by romnovi** [comment]
Also have this problem on ubuntu 16.04 x64

**Comment by bryankaplan** [comment]
Ditto on Arch.

**Comment by phipse** [comment]
Same on Fedora 23, Firefox 47.0.1;

**Comment by bskydive** [comment]
OpenSuSe don't work. Disable/enable/setup/reinstall doesn't help.

**Comment by davidhrbac** [comment]
Same FF48 Ubuntu 14.04

**Comment by RokuZero** [comment]
On debian 8.5 too

**Comment by logicalor** [comment]
Confirming, Kubuntu 16.04 FF48.0.

**Comment by davidhrbac** [comment]
Downgrade to previous version helped.

**Comment by logicalor** [comment]
Downgrade works for me in a new Firefox profile, but not in an existing profile.

**Comment by Adaephon-GH** [comment]
You can [get the previous version here](https://addons.mozilla.org/firefox/downloads/file/420541/tab_tree-1.4.6-fx-linux.xpi?src=version-history). You may have to restart Firefox after installation of the old version for it to work.

And yes, I have the same issue on Arch with FF48.

**Comment by dexterlb** [comment]
Confirmed on Arch with Firefox 48.

**Comment by bskydive** [comment]
manual install from git repo doesn't work. 
Versions list:
https://addons.mozilla.org/ru/firefox/addon/tab-tree/versions/

1.4.6 works from there!

**Comment by Bu11etmagnet** [comment]
Same with Firefox 48.0 on Ubuntu 14.04
I had to downgrade to 1.4.6

**Comment by Anbcorp** [comment]
Using git bisect, I found that commit 3056537b2fd7e306a533f258020d32f13cdb9f76 breaks the addon on my Debian Stretch with latest nightly (51.0a1 (2016-08-18))

I don't develop extensions so I can't tell why though...

**Comment by traxium** [comment]
Thanks for quick reply. Sorry didn't test it on Linux (and OS X) before uploading to AMO. I'll try to fix it as soon as possible.

**Comment by whiskybar** [comment]
I switched to a much simpler vertical tab extension https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs-reloaded in the meantime, just in case you could not downgrade and cannot wait for the fix.

**Comment by roman4e** [comment]
Does not work even after Linux fix #151. I have replaced bootstrap.js and nothing happened after reload.
FF v.48 on Mint

**Comment by traxium** [comment]
Try installing 1.4.8 from https://addons.mozilla.org/en-US/firefox/addon/tab-tree/versions/. And restart FF after it. Tested on FF 50.0a2 + Mint + Tab Tree 1.4.8:

![github - tabtree - mint](https://cloud.githubusercontent.com/assets/13660441/17809416/2026eb4c-661f-11e6-9f38-387afd2656f2.png)

**Comment by traxium** [comment]
v1.4.8 is on AMO already.

**Comment by logicalor** [comment]
Nice, v1.4.8 is working for me in Kubuntu 16.04 / FF48.0

Many thanks for the quick fix.

**Comment by ksdpmx** [comment]
:+1: v1.4.8 works on FF48.0 / ArchLinux.

**Comment by godenji** [comment]
Working again: Fedora 24 / FF Developer 50.0a2 🎉

**Comment by dexterlb** [comment]
Fix works, thanks!

**Comment by shabbyrobe** [comment]
Considering this was apparently fixed ages ago and that this extension is dead in the water since Quantum, I'm closing.
