### ISSUE TITLE
Make tab panel an actual frame.

### ISSUE THREAD

**Issue by amosbird** [traxium/tabtree#155]
When firefox's window gets shrinked, tab panel will overlie some web content, just like this.
![](https://ptpb.pw/v1Cp.jpg)

This is somehow annoying. I have to scroll horizontally to view a vital information.

**Comment by traxium** [comment]
If I understand correctly, you want to scroll horizontally to view the tabs?

**Comment by amosbird** [comment]
Hmm. I want the tab panel not overlie any content of the web page.

**Comment by Fabiensk** [comment]
I cannot reproduce this issue (Tab Tree 1.4.8, Kubuntu 16.04, KDE): the tab bar is not displayed above the content of the page for which the horizontal scrollbar is displayed properly. Which window manager are you using?
