### ISSUE TITLE
Keyboard Shortcut Syntax Documentation

### ISSUE THREAD

**Issue by AndydeCleyre** [traxium/tabtree#158]
Thanks for this!

I can't figure out how to properly specify a new keyboard shortcut for autohide, replacing F8.

The most obvious format (to me) "Ctrl+Alt+S" did not work, and I can't find this documented anywhere.

**Comment by AndydeCleyre** [comment]
Does anyone know if changing that shortcut is expected to work at this stage?

**Comment by DonyorM** [comment]
Currently keyboard shortcuts are not user configurable. From the description: "Keyboard Shortcuts (not configurable yet)".

**Comment by AndydeCleyre** [comment]
Ah, missed that, was just looking at the setting itself. Thanks.
