### ISSUE TITLE
Tabtree black after last firefox update

### ISSUE THREAD

**Issue by elbaulp** [traxium/tabtree#168]
I am using **Firefox 49.0** , _developer edition_ on Gentoo, since the last update, I am seeing a black frame when tabtree is open:

![TabTree open](https://cloud.githubusercontent.com/assets/394797/18814443/fcb329b6-8313-11e6-9251-c5cccbdc1e82.png)

When I close tabtree with F8, it works well, but firefox top panel it still black:

![F8 toggle](https://cloud.githubusercontent.com/assets/394797/18814452/2a3c1af0-8314-11e6-8fbe-53ce97caa1ba.png)

Best regards!

**Comment by gotnix** [comment]
It's an old issues, please see #151 and #160 .

**Comment by elbaulp** [comment]
Thanks
