### ISSUE TITLE
[Nightly] New tab button doesn't work

### ISSUE THREAD

**Issue by ghost** [traxium/tabtree#170]
Both the new tab button, and double-click to open a new tab, do not work in Firefox 51&52.
The errors reported to the console are, respectively:
- `TypeError: aDOMWindow.BrowserOpenNewTabOrWindow is not a function bootstrap.js:2758:4` for New Tab button.
- `TypeError: aDOMWindow.BrowserOpenNewTabOrWindow is not a function bootstrap.js:2662:7` for double-click to open a tab.

**Comment by ghost** [comment]
After some digging, it seems the following commit is responsible for the removal of BrowserOpenNewTabOrWindow: `https://hg.mozilla.org/mozilla-central/rev/cd5beac45eac`
In this commit, BrowserOpenNewTabOrWindow has been replaced by BrowserOpenTab.

It is explained in the related  [bug #528005](https://bugzilla.mozilla.org/show_bug.cgi?id=528005): « This method [BrowserOpenNewTabOrWindow] is referenced by a number of add-ons including but not limited to tabmixplus. We probably need to list it in the compat notes. »

**Comment by ghost** [comment]
I added a PR to correct the issue, but one also needs to set the minimum Firefox version to 51 for this specific change.

**Comment by traxium** [comment]
BrowserOpenNewTabOrWindow(event) was used in order to be able to open new windows while holding Shift

**Comment by traxium** [comment]
It happened that `BrowserOpenTab({shiftKey: true})` can open new windows, but it doesn't work properly with maximized windows.

**Comment by traxium** [comment]
Replaced `BrowserOpenTab(event)` with `openUILinkIn(BROWSER_NEW_TAB_URL, event.shiftKey ? "window" : "tab")`. Now it should work in all versions.
