### ISSUE TITLE
Search bar focus

### ISSUE THREAD

**Issue by f1u77y** [traxium/tabtree#172]
When search bar is hidden by default, Ctrl+Alt+Shift+F just shows it but does not focus. I think it should show and focus.
Also, when search bar is hidden, Escape when bar is focus works correctly(unfocuses and hides search bar). But when it's not hidden by default, Esacpe does nothing when it's focused

**Comment by traxium** [comment]
When search bar is not hidden and there's some text in it, Escape clears that text.
