### ISSUE TITLE
Firefox 49 crashes when leaving full screen video in certain conditions 

### ISSUE THREAD

**Issue by Fabiensk** [traxium/tabtree#176]
Maybe related to #173 .

- From default settings, configure Tab Tree to be displayed on the left (no problem when displayed on the right).
- Open a good number of tabs (about:blank is ok)
- Open a page with an HTML5 video (like [this one](http://iandevlin.github.io/mdn/video-player-with-captions/))
- Reduce the height of the window so a scrollbar is displayed in the tab panel.
- Play the video, put it full screen, then press Escape or click the button to leave the full screen mode. => Firefox crashes

Conguration: Firefox 49.0.2 under Kubuntu 16.04 amd64 with a new Firefox profile. Also crashes with Firefox 50.0b11.
No problem with Firefox 51.0a2

**Comment by traxium** [comment]
Couldn't confirm on FF 49.0.2 Mint 18 VMware. What's your video card manufacturer, Intel? The discussion will be in #173.
