### ISSUE TITLE
Remove any options that aren't strictly suitable to this add-on

### ISSUE THREAD

**Issue by Keith94** [traxium/tabtree#179]
After scrolling through all the options, the following ones don't seem to have any relation to the main "Tab Tree" feature of this add-on, so I'm not sure why they are included at all..

* Highlight unloaded tabs
* Highlight unread tabs
* Double click on a tab
* Middle-click on the tabbar
* Navigation bar height
* Show the "Close tab" buttons
* Tab flip

**Comment by Bu11etmagnet** [comment]
Umm, what? Are you saying there should be a separate add-on for each of
-    Highlight unloaded tabs
-    Highlight unread tabs
-    Double click on a tab
-    Middle-click on the tabbar
-    Navigation bar height
-    Show the "Close tab" buttons
-    Tab flip

?

**Comment by Keith94** [comment]
I'm saying these features don't strictly belong in **this** add-on, and most of the features are already provided by other add-ons, or can be implemented by the user with CSS with better results.
