### ISSUE TITLE
Invisible audio playback on-tab indicator

### ISSUE THREAD

**Issue by allixx** [traxium/tabtree#194]
Tab Tree 1.4.8 / Firefox 51.0 x64 / Win7. On-tab audio playback indicator is invisible (just an empty space instead of the icon) when this audio tab is active. You still can click it to mute/unmute sound though. 
Themes: Default / Try to mimic the Firefox theme.

No such problem existed in Firefox 50 x64 / Win7.

**Comment by albin-engstrom** [comment]
Same here after an update to Firefox 51.

Tab Tree 1.4.8. 
Arch Linux.

**Comment by OmTatSat** [comment]
Do you have this bug with "Try to mimic the Firefox theme"?
For me this theme show audio playback indicator.
I edited dark theme to show audio playback indicator too, tested with cyberfox 51 x64

**Comment by OmTatSat** [comment]
Here is edited file  https://cloud.mail.ru/public/iydU/L8y4FVVUM

**Comment by albin-engstrom** [comment]
For me it doesn't work with any of the themes.

**Comment by OmTatSat** [comment]
check this 
about:config
browser.tabs.showAudioPlayingIcon
true

**Comment by albin-engstrom** [comment]
That's already set to true.

**Comment by OmTatSat** [comment]
do you see audio playback indicator without tab tree?

**Comment by OmTatSat** [comment]
![1 06-02-17 19 25 54](https://cloud.githubusercontent.com/assets/25341911/22658245/207dbc56-eca2-11e6-9e71-761f2037d57e.PNG)

**Comment by OmTatSat** [comment]
I use https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/
may be this help me to see audio playback indicator...

**Comment by albin-engstrom** [comment]
The indicator works when using normal tabs.

The Classic Theme Restorer does not make the indicator show up.

**Comment by OmTatSat** [comment]
try import my settings in Classic Theme Restorer
[CTRpreferences+.txt](https://github.com/traxium/tabtree/files/755423/CTRpreferences.txt)
"Try to mimic the Firefox theme"
maybe restart...
