### ISSUE TITLE
Crashes Firefox 54

### ISSUE THREAD

**Issue by tgoltz** [traxium/tabtree#215]
Tab Tree 1.4.9 causes Firefox 54 to crash at startup.  I was running Tab Tree with Firefix 53.0.3, and it was working fine.  I upgraded to 54, and it crashed at startup.  I wasn't able to run 54 until I disabled Tab Tree, and Firefox 54 immediately crashes if I re-enable it.  This happened under Windows 7 x64.

Once I reverted to Firefox 53.0.3, everything was fine again.

**Comment by polyzen** [comment]
Works on Linux.

**Comment by tgoltz** [comment]
Only other item is that I am running Microsoft EMET 5.5.

**Comment by tgoltz** [comment]
I saw some other weird behavior out of Firefox, so I blew away my profiles and did a clean install, and the crash went away.  There might be a problem, but I have no idea what's causing it in my profile, so I'm closing this out.
