### ISSUE TITLE
Firefox 55 - back button missing

### ISSUE THREAD

**Issue by simbin** [traxium/tabtree#220]
Back button is missing/blank in Firefox 55

**Comment by narwhalofages** [comment]
Can confirm issue in Firefox Nightly on Ubuntu, all other add-ons disabled.

![screenshot from 2017-08-10 02-45-14](https://user-images.githubusercontent.com/16219814/29165038-410cecd4-7d76-11e7-819b-beebeb9324d6.png)

**Comment by TempSpas** [comment]
I updated to 1.5.0 and the back button is still missing. I'm on Firefox 55.0.1, macOS 10.12.6, using the compact dark theme if it helps.

Screenshot of it still happening:
<img width="782" alt="screenshot" src="https://user-images.githubusercontent.com/3801275/29243449-2b17b3ac-7f6d-11e7-9c58-196641c0a05c.png">

**Comment by traxium** [comment]
Yes, it helped, I fixed only Windows and Linux versions. I didn't have a chance to check whether it was broken or not on macOS. I'll look at it today.

**Comment by traxium** [comment]
Btw, there's a quick fix:
1. about:addons -> Appearance -> Compact Dark -> Enable
2. right-click Navigation Bar -> Navigation Bar height -> Default (40px in the default theme)
![macos](https://user-images.githubusercontent.com/13660441/29245335-ec82d522-7fdf-11e7-96b3-98d5d7e8a74b.png)

**Comment by narwhalofages** [comment]
AMO has this marked as incompatible with Nightly, but I was able to download it in another version and manually install it. Looks like that fixed it for me!
