### ISSUE TITLE
Make installable for Firefox 55

### ISSUE THREAD

**Issue by AndydeCleyre** [traxium/tabtree#221]
![image](https://user-images.githubusercontent.com/1787385/29196261-3468edf8-7e01-11e7-8d34-64b07d11a145.png)

**Comment by polyzen** [comment]
Worked for me.

**Comment by AndydeCleyre** [comment]
I just created a new profile, and immediately went to the addons page:

![image](https://user-images.githubusercontent.com/1787385/29204238-cf51c19a-7e43-11e7-945d-571fe45bb04f.png)


Arch Linux, FF 55.0

**Comment by polyzen** [comment]
Try https://addons.cdn.mozilla.net/user-media/addons/637996/tab_tree-1.4.9-fx-linux.xpi

Edit: I see the Firefox page says, "Works with Firefox 26.0 - 51.0," for some reason.

**Comment by AndydeCleyre** [comment]
Yeah, that works, thanks. We should get the addon page working, though I'm not sure where that version compatibility status is specified.
