### ISSUE TITLE
FF55 - Tabs from previous session do not restore on launch

### ISSUE THREAD

**Issue by jayywolff** [traxium/tabtree#222]
Arch Linux x86_64 
Kernel 4.12.4
Firefox 55.0 (64-bit)

If you use the 'Show your windows and tabs from last time'  option, when launching firefox tabs do not restore. All I get is a white bg with a loading spinner centered (even after refreshing the page) for all my open tabs. Even with the dev tools open and the network tab showing the DOM is fully loaded, all i get is a loading spinner...

I can close the tab and open the site in a new tab but this defeats the purpose of restoring tabs on launch.
The only way to fix it completely is to disable tabtree.

This bug is a deal breaker for me, I have to disable the tab tree extension  😢 

Wow Mozilla, I can't use tab tree, vimperator, or the arc-dark theme anymore as of FF 55. I'm on the verge of switching back to vivaldi at this point..

**Comment by polyzen** [comment]
Works for me.

**Comment by jayywolff** [comment]
This may have been somewhat un-related to tabtree 

There was an update today to FF 55.0 -> 55.0.1 and in the announcements from Mozilla they claim to have fixed the bug I was describing here.

https://www.mozilla.org/en-US/firefox/55.0.1/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_campaign=whatsnew

"Fix a regression the tab restoration process (bug [1388160](https://bugzilla.mozilla.org/show_bug.cgi?id=1388628))"


However I completely nuked my ~/.mozilla dir to give Firefox a fresh start and now I am unable to install the tabtree extension so I cannot verify that the issue went away. Either way I haven't had the bug since I uninstalled tabtree.

**Comment by polyzen** [comment]
https://github.com/traxium/tabtree/issues/221#issuecomment-321746670

**Comment by jayywolff** [comment]
@polyzen thank you, I had previously looked at that thread yesterday, but had not checked for updates there. Got it installed again. Ill go back to using it for as long as I can, and ill close this issue if all is good within a few days.

**Comment by jayywolff** [comment]
Ive still been getting the issue with tabs not restoring but I found out how to re-produce the bug. And it makes no difference if I have tabtree enabled or disabled.

I've noticed that anytime I start or kill compton (my X11 compositor) All my firefox tabs blank out and even with a page refresh will not restore. I have to close and reopen firefox to get my tabs back.
