### ISSUE TITLE
Small border in Fullscreen mode

### ISSUE THREAD

**Issue by lePoMo** [traxium/tabtree#24]
With the tab-list hidden in fullscreen mode, there's still a small line/border visible.

Seeing as html5 video players like Youtube use the browser's fullscreen mode to show a video in fullscreen, that small bright border sticks out (and is hence bothering me).

I assume it is used as a workaround to be able to hover over it (and by that expand it).

Solutions I can think of (in order of preference, if possible):
- ideally, do without that small border
- add an option to disable the hover-to-pop-in feature (which i assume would make the border not show)
- have it be colored black or configurable color (that would do on my screen, but possibly not on all screens)
- might be ok from a UX pov, or might be weird: if you can hook into firefox showing the navigation-bar (when moving the mouse to the top of the screen), have its visibility linked to that.

**Comment by traxium** [comment]
You are right. I just did what Firefox does for its navigation bar. But Firefox places this 1px black (mine is transparent) line at the top. And I place it to the left or right.
And what I missed is that Firefox hides this tiny black line while playing Youtube in fullscreen mode (so you can't pop up the navigation bar while Youtube is maximized). Tab Tree should do the same. Ok, as soon as I figure out how Firefox does it, I repeat it for the tab tree panel. Thank you for mentioning it.

**Comment by traxium** [comment]
If nobody has anything to say I'll close the issue.

**Comment by lePoMo** [comment]
Sorry for not having commented after you implemented the change, I wasn't (and still am not) sure about etiquette on github (like wether a "thank you" comment is frowned upon because it doesn't add the issue).

I'll go now:
Thank you. I confirm that the changed behavior corresponds to what I had hoped for and that I am not experiencing any issues introduced by this change.

Thank you :)
