### ISSUE TITLE
Hide tabtree bar on popup window

### ISSUE THREAD

**Issue by hsantanna** [traxium/tabtree#33]
Add option to hide tabtree bar on popup window and also hide when there is only one open tab.

**Comment by GeorgeHahn** [comment]
I agree, it would be really nice if the bar automatically hid when there was only one tab open.

**Comment by motofix** [comment]
My webmail client is opening a popup when writing a new mail, with half space used by TabTree. Hidding TabTree when only one tab is opened  would definitively be a nice feature :-)

**Comment by traxium** [comment]
I added an option to hide the tab tree when there's only one tab (at the very bottom in the add-on options). By default it's disabled. I thought some users could be frustrated if there's no the "Open a new tab" button (?). So you should enable it manually. This option will be available in version 1.3.9.

**Comment by motofix** [comment]
Thanks! Can't wait for the 1.3.9 ;-)

**Comment by traxium** [comment]
If nobody has anything to say I'll close the issue.

**Comment by motofix** [comment]
Works like a charm here, thank you!
