### ISSUE TITLE
[Bug] Does not work with a dark theme

### ISSUE THREAD

**Issue by pitman10** [traxium/tabtree#35]
I'm using FT DeepDark - https://addons.mozilla.org/en-us/firefox/addon/ft-deepdark/ and it makes tab tree look like this http://pasteboard.co/1on9fOLx.png

**Comment by Boolean263** [comment]
I'm having a look at adjusting the CSS to make it more theme-friendly. Unfortunately, some of the onus is on the theme writers to support the add-on and the new elements it adds. If I take out all the custom CSS, then it loses the look that Traxium was originally going for.

**Comment by Boolean263** [comment]
I did my best in [this push](https://github.com/Boolean263/tabtree/commit/881dfcf2d6357bd6275b1699d423ce1c0a9115e3). Unfortunately as noted there, we need to keep the background colour on the tree itself for now, and encourage themers to override it.

**Comment by traxium** [comment]
If nobody has anything to say I'll close the issue.
