### ISSUE TITLE
[Feature] Middle click on empty space to open a new tab

### ISSUE THREAD

**Issue by pitman10** [traxium/tabtree#36]
Had this feature on Tree Style Tabs which is convenient and would like to see it in Tab Tree as well.

**Comment by traxium** [comment]
As there was no action assigned to middle-click on empty space so I just added it without any option.

**Comment by haarp** [comment]
May I request to have the option for middle-click to undo close tab instead? That's what my TST is set to.

**Comment by traxium** [comment]
If nobody has anything to say I'll close the issue.

**Comment by haarp** [comment]
Just tested it. Works very well, Thanks a lot! :)
