### ISSUE TITLE
[Bug]Ctrl+drag to duplicate tab

### ISSUE THREAD

**Issue by kshpytsya** [traxium/tabtree#39]
Firefox's native tab bar allows a not-so-intuitive way of duplicating a tab by doing a Ctrl+drag (personally I would rather have a context menu option). With TabTree, Ctrl+drag seems to have a different cursor (with "+" in it) as compared to ordinary drag but actual duplication does not occur.

**Comment by strigona-worksight** [comment]
Seconded.

I believe this was disabled around when @traxium disabled dragging tabs between windows.

**Comment by traxium** [comment]
Done. But Ctrl+drag duplicates only one tab despite its feedback image. I decided that there are very few people who want to duplicate a whole subtree and it was much easier to implement with just one tab.
And also I added tab context menu items to duplicate a tab:
1. as a child
2. as a sibling
3. to the bottom of the tree

**Comment by traxium** [comment]
If nobody has anything to say I'll close the issue.
