### ISSUE TITLE
with dev edition (44.0a2), clicking on tab doesn't switch to it

### ISSUE THREAD

**Issue by willkg** [traxium/tabtree#43]
I just upgraded to dev edition 44.0a2 and tree-style-tabs broke everything, so I removed that and switched to Tab Tree 1.3.6 which seems a lot better. (Thank you!)

My one problem is that left-clicking on tabs doesn't switch to the tab. I can only switch tabs by pressing ctrl-pgup/ctrl-pgdwn.

What else can I tell you to help figure out the issue? Any ideas on what it might be?

**Comment by tumpio** [comment]
I'm not on the developer edition, but this happens to me when I open another tab group. After removing other tab groups, tabs are again switchable by left click. This is reproducible.

I'm using Firefox 42.0 and Tab Tree 1.3.6

**Comment by willkg** [comment]
Hot dog--turns out I had multiple tab groups that I probably fiddled with years ago but then forgot about. My bad. I'll close this out. Thank you!
