### ISSUE TITLE
Pinned tabs on mutliple lines

### ISSUE THREAD

**Issue by xurei** [traxium/tabtree#45]
I have a lot of pinned tabs (about 20). With the extension, they should appear on multiple lines. Right now it doesn't.

**Comment by faulesocke** [comment]
Actually it's a bug that they don't appear on multiple lines because like it's now, not all pinned tabs are shown.

**Comment by xurei** [comment]
Exactly, my previous message was not really clear.

**Comment by xurei** [comment]
I'm working on a fix for this. I have something working, but I'm stuck on a bug when I remove the pinned tabs.
I've modified the code so that there can be multiple toolbars in the toolbox. There is some things to improve, but it works. However, I've got weird behaviours when I close a pinned tab. 
I don't really understand how the closing mechanism works. Is it something native, or is it implemented somewhere ?

**Comment by traxium** [comment]
When a tab is being closed Firefox invokes `gBrowser._endRemoveTab()` and right after it I invoke `tt.redrawToolbarbuttons()` (I use `Proxy` to "intercept" `gBrowser._endRemoveTab()`). `tt.redrawToolbarbuttons()` redraws all pinned tabs. I.e. roughly speaking every time a pinned tab is closed (or added or selected) `tt.redrawToolbarbuttons()` removes all existing "buttons" corresponding to pinned tabs and creates new "buttons" corresponding to pinned tabs from the scratch. And by the way there were some changes in `tt.redrawToolbarbuttons()` in the last commit (dc06b94a91111d27560732f342108fdfc2c09a20).

And as one solution to this issue I have been suggesting replacing `<toolbox>` and `<toolbar>` with something like a horizontal list (`<ul>` and `<li>` with `li {display: inline;}`) or something else with CSS `{display: inline-block}`. But I didn't have time to try it out.

**Comment by xurei** [comment]
Thanks for those precisions. 
My prototype is nearly ready. I still have one weird bug : when I close a pinned tab, it closes the pinned tab before this one. For a normal tab, no problem. 
Is there something done about the contextual menus of pinned tabs that are not with normal tabs ?
Also, can you explain what hboxForDropIndicator is for ? I don't see what's its purpose.

**Comment by traxium** [comment]
When you drag and drop something to pinned tab bar a black arrow appears. That hboxForDropIndicator is for that arrow. And `hboxForDropIndicator` is always the first invisible child of `toolbar` (therefore the first "button" is the second child of `toolbar`, the second "button" is the third child and etc.). And there are a lot of comments like `// +1 for the arrow hbox` warning about that.

**Comment by traxium** [comment]
If nobody has anything to say I'll close the issue.
