### ISSUE TITLE
Top Toolbar Cutoff Slightly

### ISSUE THREAD

**Issue by strigona-worksight** [traxium/tabtree#5]
As you can see in the screenshot below, the overlayed numbers for a number of addons is being cutoff. I am using Classic Theme Restorer in the screenshot below, but have tested without and it's still cutoff in the same way. I think there needs to be a little bit more padding on the top.

![Screenshot](http://i.imgur.com/CAJTFSe.png)

**Comment by traxium** [comment]
By the way, Mozilla fixed this problem in Firefox 42.0+:
![padding](https://cloud.githubusercontent.com/assets/13660441/9340317/ad8792be-45f7-11e5-9d46-70028399eda7.png)

**Comment by strigona-worksight** [comment]
Awesome - even better!
