### ISSUE TITLE
Add a way to open a new tab as a child of the current tab

### ISSUE THREAD

**Issue by mythmon** [traxium/tabtree#52]
I use tree style tabs to group tabs into tasks and sub tasks. This means a lot of the time I open a new tab but want to keep it in the same part tree. It would be great to have a way to open tab as a sibling of the current tab, as a child of the current tab, or as a new top level tab.

Maybe this can be an option for what is the default. Or maybe there can be multiple hotkeys/buttons to open new tabs that control what behavior is taken.

**Comment by traxium** [comment]
I added two context menu options (right-click a tab to access them):
1. Open a new tab as a child (opens a new tab as the last child)
2. Open a new tab as the next sibling (opens a new tab as a sibling next to the current tab)

**Comment by traxium** [comment]
Is this solution convenient? They will be available in version 1.4.0.

**Comment by traxium** [comment]
If nobody has anything to say I'll close the issue.
