### ISSUE TITLE
Option to select next tab in the same child level after closing current tab

### ISSUE THREAD

**Issue by wzol** [traxium/tabtree#56]
I got used to a browsing style where I open many child tabs from a site (from Google example), then browse them one by one. With Tree Style Tabs I could accomplish this with a "stay in child level when closing a tab" or a similar named option. Could you add something similar?

**Comment by haarp** [comment]
Disabling FLST works for me.

**Comment by wzol** [comment]
Yes, I have tried that too. The problem is that if you have many childs, and you close the first, it won't stay in the child level.

**Comment by traxium** [comment]
The option will be available in v1.4.2.

**Comment by wzol** [comment]
Yess! That is awesome, thank you very much, can't wait to try it! :)
