### ISSUE TITLE
[Ubuntu Linux] Gap at the top of the tree tab bar

### ISSUE THREAD

**Issue by CanadianJeff** [traxium/tabtree#58]
Versions

```
Firefox Version 42
Tab Tree 1.4.0
```

Screenshot
![Screenshot](http://i.imgur.com/ZFa4A6Z.png)

**Comment by traxium** [comment]
It's already fixed, but not uploaded to addons.mozilla.org. The fix will be in the next version (1.4.1). By the way, look at issue #22 for more information (It's actually pinned tabs toolbar at the top).

**Comment by CanadianJeff** [comment]
when do you think you could have 1.4.1 uploaded to addons?

**Comment by traxium** [comment]
It's not ready yet (and not fully tested). And I'll probably be in hospital in the next few days.

**Comment by traxium** [comment]
I uploaded 1.4.1b on beta channel (https://addons.mozilla.org/en-US/firefox/addon/tab-tree/versions/?page=1#version-1.4.1b).

**Comment by CanadianJeff** [comment]
fixed in the beta closing feel free to re open
