### ISSUE TITLE
[Bug] Dragging a Tab between Windows Breaks Tree

### ISSUE THREAD

**Issue by strigona-worksight** [traxium/tabtree#6]
Dragging a tab from one window to another window is visually possible, but after you do that, both the new and old window get out of sync in weird ways. Unsure if this will be resolved in 1.2.2.

**Comment by strigona** [comment]
I just tested this in 1.1.4 and I believe it is resolved (sorry - I keep jumping back and forth between personal & work account).

**Comment by traxium** [comment]
I noticed that It gets out of sync if the tab being moved to another window (context menu -> "Move to New Window") is unloaded. And that tab keeps its indent level unchanged in a new window.
And if tabs are dragged by mouse then it sometimes allows dropping and sometimes doesn't. And sometimes dropping has no effect and sometimes it breaks the tree in weird way.

**Comment by traxium** [comment]
I disabled dragging tabs between windows for now. And fixed problem with "Move to New Window" in 522636a. And I almost figured out how Firefox moves its default tabs between windows and I'll do it when more urgent issues is resolved.

**Comment by traxium** [comment]
Now it works and the issue should be closed.
