### ISSUE TITLE
Garbage in menu items

### ISSUE THREAD

**Issue by tioteath** [traxium/tabtree#60]
Current behavior: Tabtree's menu items are prefixed with `Tab Tree:`
Expected behavior: No garbage should be present in menu items.

**Comment by traxium** [comment]
Do you want tab tree menu items to look like this?
![garbage](https://cloud.githubusercontent.com/assets/13660441/12050813/6ad764f8-af0b-11e5-970d-d30bab0a35ba.PNG)

**Comment by tioteath** [comment]
Exactly. That would be great to have it like this. Thank you.

**Comment by DaRoni** [comment]
for me as it is convenient

**Comment by traxium** [comment]
It seems I should create an option to enable/disable "Tab Tree: " prefix, should it be disabled or enabled by default?
I decided to include this prefix in order if a user has many add-ons installed and many tab context menu items added he could see where each new menu item came from.

**Comment by tioteath** [comment]
> It seems I should create an option to enable/disable "Tab Tree: " prefix, should it be disabled or enabled by default?

I'm going to say "Yes". In my opinion, those items should not be displayed by default.

> I decided to include this prefix in order if a user has many add-ons installed and many tab context menu items added he could see where each new menu item came from.

From the user perspective, I'd like to not be aware about extensions. I'd like to use a specific functionality, i.e. apply some action on a tab in that case, and it's not really important for me how this functionality is achieved. It probably could be a good reason in case of multiple extensions with the same functionality, only I can hardly  imagine what these extensions could be in case of "Tab tree". I can see four prefixed items that are very specific about organizing tabs in the tree, i.e. "Close tree/children" and "Open a new tab  as  the next sibling /a child". I really doubt it's possible to install another tree-like extension and have a good result on that.
On the other hand, it hurts usability, as after I open menu and search for an item, the first thing I should search for is a "Tab Tree" prefix, and then look for specific item I'm interested in. It takes like 1/3 second more to archive.

**Comment by traxium** [comment]
If nobody has anything to say I'll close the issue.
