### ISSUE TITLE
Feature request: Background colors

### ISSUE THREAD

**Issue by ivoshm** [traxium/tabtree#62]
TabTree is IMHO a great idea how to change usual behavior of browser tabs.

His background colors are based on color palette of webpage pane now (usually black on white).

I propose to add to the configuration choice to switch default look of TabTree to color theme based on main browser colors (as they are used in menus and toolbars).

I have very limited knowledge of internal of Firefox - but temporarily I hack this in userChrome.css:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
#tt-treechildren {
    background-color: #e4f5ff;
}
```

(used color is similar to color of my toolbar background)

**Comment by traxium** [comment]
It's already done to some extent in v1.4.1b.

**Comment by traxium** [comment]
In version 1.4.2 Tab Tree uses something like this (if the options "Try to mimic the Firefox theme" is selected):

``` CSS
.tt-treechildren,
.tt-treechildren::-moz-tree-row {
    background-color: var(--tab-background-color);
}
```

The list of Firefox defined CSS variables that are used:

``` CSS
/* Chrome */
--chrome-secondary-background-color
--chrome-nav-bar-controls-border-color

/* Tabs */
--tabs-toolbar-color
--tab-background-color
--tab-hover-background-color
--tab-selection-color
--tab-selection-background-color
--tab-selection-box-shadow

/* Url and search bars */
--url-and-searchbar-background-color
--url-and-searchbar-color
```

**Comment by ivoshm** [comment]
Thanks Traxium - it works.
