### ISSUE TITLE
Cannot move tab with ctrl-shift-pageup/down

### ISSUE THREAD

**Issue by nyanpasu64** [traxium/tabtree#68]
I constantly move tabs with ctrl-shift-pageup/down. This feature is available in vanilla Firefox, available but buggy in Tree Style Tab, but disabled in this extension. This is a show-stopper for me. which is unfortunate because I'm interested in a less buggy alternative to TST.

Note, in TST, ctrl-shift-PU moves a tab into a tree when the tab ends up adjacent to the tree. I'd prefer for it to enter into a tree when moved UP above an existing tree member, and exit when moved DOWN below the last tree member.

It would be nice to add shortcuts for, in decreasing order of importance for me, "move tab out one level, shifting down if needed" and "move tab into tree".

**Comment by jjeziorny** [comment]
Also looking for this, being very keyboard orinted it's important to be able to re-organize your tabs using the keyboard only.
This is the standard behaviour in FF even without any tab management addon, so it would be great if it continue to work when using tabtree.

**Comment by traxium** [comment]
Done. It'll be available in the next version (1.4.3).
- Ctrl+Shift+PageUp/Down — moves tabs as expected (from my understanding)
- Ctrl+Alt+Shift+PageUp/Down — moves tabs "slow", i.e. entering a subtree wherever it's possible
- Shift+Alt+PageUp/Down — moves tabs "fast", i.e. not entering subtrees
- Ctrl+Alt+PageUp/Down — isn't used

You can "move tab into tree" using Ctrl+Alt+Shift+PageUp/Down and "move tab out one level, shifting down if needed" using any keyboard shortcut (e.g. Ctrl+Shift+PageUp/Down, they actually behave identically when moving tabs out of a subtree).

**Comment by traxium** [comment]
- Ctrl+Shift+Left/Right — decreases/increases the indentation level of a current tab

**Comment by traxium** [comment]
The big is fixed. I'll close the issue. By the way Ctrl+Shift+Left/Right is changed to Ctrl+Shift+,/. in another issue.
