### ISSUE TITLE
Gif animations don’t animate

### ISSUE THREAD

**Issue by raphaelbastide** [traxium/tabtree#69]
Gif animations are blocked if the image is opened in a dedicated tab.
- Disabling Tabtree solve the problem.
- I have the intuition it is related to the favicon (which is supposed to be the same animation). 

Tested on GNU/Linux Manjaro XFCE on Firefox 42.0

[Test image](http://www.doggifpage.com/gifs/117.gif).

**Comment by traxium** [comment]
It doesn't work in FF 43.0.4. But it works in FF 46.0a1 (2015-12-30).

**Comment by traxium** [comment]
Fixed. The fix will be available in the next version (1.4.3). Thank you for reporting this bug.
And also from now on animated favicons will animate on all tabs (until now they animated only on pinned tabs).

**Comment by traxium** [comment]
So the bug is fixed in [v1.4.3](https://github.com/traxium/tabtree/releases/tag/v1.4.3). I'll close the issue.
