### ISSUE TITLE
You may want to use rectangular "Back" button And/OR don't "compress" it

### ISSUE THREAD

**Issue by arni2033** [traxium/tabtree#7]
Currently, (as I see) you're just setting fixed height to the toolbar, and therefore the "back" button "compresses". I mean, the image that is used in "back" button is normally 18x18 and after installing your add-on it becomes ~18x14.
You may want to use my userstyle "Thin toolbar" from this folder as a reference OR
use Browser Toolbox in Firefox that allows to explore GUI elements "on the fly"
https://www.dropbox.com/sh/lnyqbhaq08l7ecx/AAB-O26DJzV0gFtbp3WYT4vma?dl=0
https://developer.mozilla.org/ru/docs/Tools/Browser_Toolbox

Возможно, по-русски это будет понятнее.
Я предлагаю улучшить вид кнопки "Назад", которая сейчас выглядит "сжатой", видимо, из-за неудобства работы с CSS браузера. Поэтому я предлагаю свой стиль "Thin toolbar" как пример, а также - инструмент браузера, который позволяет исследовать элементы GUI "на лету".

**Comment by traxium** [comment]
Мне хочется сделать так, чтобы можно было подвести мышку в упор к верхнему краю экрана, кликнуть его и при этом чтобы выделился текст в адресной строке (или строке поиска, смотря над чем находилась мышка в момент клика). Это всё естественно должно работать, если окно Файрфокса развёрнуто и сверху нет панели задач. А насчёт кнопки "назад" согласен, лучше сделать её квадратной и не сжимать её.
А "Browser Toolbox"-ом я пользуюсь каждый день, там же дебагер рядом и консоль, но я не знал что там можно редактировать стили во вкладке "Style Editor" на лету. Там, оказывается, можно нажать кнопку "New" и писать что хочешь и всё будет сразу применяться. Если бы я знал это раньше, я думаю, некоторые вещи я сделал бы значительно быстрее. Спасибо за наводку.
Но Firefox 40.0.2 у меня почему-то иногда перестаёт обновлять стили "на лету" и мне приходится закрывать и снова открывать этот Browser Toolbox, чтобы стили снова начали обновляться.

**Comment by arni2033** [comment]
Да, я видел. На данный момент, если кликать правой кнопкой на самый верх приложения (Win7, развёрнутое окно, без Title Bar), то открывается контекстное меню окна, а не тулбара.
В Location Bar откуда-то возникла тёмно-серая полоса; про неё уже написали на странице дополнения https://i.imgur.com/WmC66e1.png
_Может быть_ я смогу как-то помочь с серой полосой да и вообще с Location Toolbar, но, если честно, времени у меня маловато. 

Насчёт Browser Toolbox - лично я использую DevEdition42.0a2, там всё это наверное чуть стабильнее. Ещё использую Stylish, чтобы закреплять заведомо "хорошие" изменения
(Там надо указать пространство имён XUL и @-moz-document. Ну как у меня в примерах)

**Comment by traxium** [comment]
Это же я сам эту серую полосу добавил. Эти параметры я нашёл в недрах Firefox. И как мне показалось, по задумке Firefox такие параметры должны создавать эффект утопленности:

``` css
#urlbar,
.searchbar-textbox {
    border-width: 2px;
    -moz-border-top-colors: #ACA899 #716F64;
    -moz-border-right-colors: #FFF #F1EFE2;
    -moz-border-bottom-colors: #FFF #F1EFE2;
    -moz-border-left-colors: #ACA899 #716F64;
}
```

**Comment by arni2033** [comment]
Эм, ну это для какой-нибудь XP. В общем, людям не слишком понравился old-style дизайн. Я ещё могу вбросить ссылку с небольшим обсуждением, и отзывы там были не очень лестные.
   Могу тут предложить не делать дополнительных "фич", либо сделать возможность от них отказаться. Ведь многие привыкли к старому виду тулбара, и для его настройки есть специальные стили на userstyles.org.

   Кстати, у меня на Win7 правый клик по верхней строчке вызывает контекстное меню приложения. Я не получил ответ, поэтому напишу подробнее.
На скринах видно, что это вызвано тем, что #titlebar имеет высоту 27, а margin-bottom: -26 (насчёт padding-top сам не уверен). Если я меняю margin-bottom на -27, всё нормально. Видимо, в развёрнутом окне нужно следить за высотой #titlebar и устанавливать соответствующий margin-bottom. (и за пользовательскими настройками тоже придётся следить, потому что юзер может выбрать отображение Menu Bar и Titlebar)
[1 screenshot](https://cloud.githubusercontent.com/assets/9205283/9407651/0a89cc52-4814-11e5-833a-5147c6206f36.png)
[2 screenshot](https://cloud.githubusercontent.com/assets/9205283/9407655/0d62e080-4814-11e5-8f3a-d90f9a538b4a.png)
[3 screenshot](https://cloud.githubusercontent.com/assets/9205283/9407658/0ed971fe-4814-11e5-917c-e3a3723b81d9.png)
[4 screenshot](https://cloud.githubusercontent.com/assets/9205283/9407662/1073dac2-4814-11e5-9e7f-728fdc3c8e1a.png)
   Ещё можно, конечно, сдвинуть #navigator-toolbox вверх, установив margin-top: -1px, но из-за этого ломается показ тулбара в фуллскрине. Чтобы её вылечить, можно, наверное, увеличить высоту #fullscr-toggler с 1px до 2px... Но сдвигать #navigator-toolbox вверх стоит только в #main-window[sizemode="maximized"] потому что в нормальном режиме из-за этого перестаёт отображаться верхняя граница #navigator-toolbox

**Comment by arni2033** [comment]
Вот кстати баг на Windows насчёт контекстного меню приложения
https://bugzilla.mozilla.org/show_bug.cgi?id=1171467

Напоследок скажу, что лично я обычно открываю новое окно, и уже для него открываю Browser Toolbox, потому что отладчиком я пару раз ломал окна. Фича хоть и крутая, но ещё сырая.

**Comment by traxium** [comment]
В следующей версии я сделаю опцию не применять мои стили для #nav-bar. А этот отрицательный маргин Firefox рассчитывает сам в updateTitlebarDisplay() который вызывается при каждом отображении/скрытии меню, насколько я помню.
И на ваших скриншотах, мне кажется, что размер кнопок свернуть/развернуть/закрыть больше стандартного в Windows 7 и навбар растягивается под их размер. Но в любом случае я уберу:

``` css
#nav-bar {
    height: 27px;
}
```

но пока что меня задерживает эта круглая кнопка, я вчера весь вечер пытался сделать её квадратной, но так и не смог. Только в самом конце я понял что проблема была в `clip-path` на #urlbar-wrapper в browser.css:

``` css
window:not([chromehidden~="toolbar"]) #urlbar-wrapper {
    clip-path: url("chrome://browser/content/browser.xul#urlbar-back-button-clip-path");
    margin-inline-start: calc(-1 * var(--backbutton-urlbar-overlap));
}
```

И ещё надо поправить баг в Windows 8, когда вместо свернуть/развернуть/закрыть отображается пустое поле. Думаю придётся сделать, чтобы при отображении меню, эти кнопки перемещались в меню, а не оставались на навбаре. Так что до исправления этого бага, трогать эти маргины не имеет смысла.

В 43.0a1 Browser Toolbox работает действительно стабильнее, чем в 40.0.2.

**Comment by traxium** [comment]
If nobody has anything to say I'll close the issue.
