### ISSUE TITLE
Be more compatible with keyboard-oriented addons such as VimFx

### ISSUE THREAD

**Issue by idlewan** [traxium/tabtree#73]
I'm a VimFx user (which emulates Vim keybindings so that you can control the browser mostly by keyboard instead of relying on clicking on things).

Whenever I open a new tab through VimFx's hint feature (when you press 'F' , hints bubble appear on the page, when you press the letters from a bubble it opens the link in a new tab), the tab opens at the bottom of the tree, at the top level, instead of opening under the current tab.
Middle-clicking on links in a page opens them under the current tab, so works fine.

Would there be a way to put the tabs opened through keyboard-interaction underneath the current tab as well, just like it works for tabs opened through clicking on links?

**Comment by tumpio** [comment]
I think you can control this from VimFx. f-key to open in same tab, F (shift+f) to open in new tab. Do they work as expected?

**Comment by meekreau** [comment]
Just an experience report from a Vimperator user: works as expected (i.e. correct indentation), tested in a clean profile with only Vimperator and Tab Tree installed. Keystrokes used: ;t<hint-number>

**Comment by traxium** [comment]
The fix will be available in v1.4.6. Thank you for reporting the bug, sorry for making you wait so much time. Tested with 'f' (open tab in a current tab), 'F' (open tab in a new background tab), 'gf' (open tab in a new foreground tab).

**Comment by ghost** [comment]
Hello. Would it also be possible to take a look at the 'zF' key combination of VimFx? It should open hints on all clickable elements in the browser chrome but it doesn't work for the normal tabs that TabTree creates. The pinned tabs work fine.

**Comment by traxium** [comment]
Yes. All normal tabs are one big `<treechildren id="tt-treechildren">` element:

``` HTML
<tree id="tt" flex="1" seltype="single" context="tabContextMenu" treelines="true" hidecolumnpicker="true">
    <treecols>
        <treecol /> <!-- titles -->
        <treecol /> <!-- audio indicators -->
        <treecol /> <!-- close buttons -->
        <treecol /> <!-- scrollbar -->
    </treecols>
    <treechildren id="tt-treechildren"/>
</tree>
```

Sorry, it's impossible to access an individual tab in that way as it is. But there was #90 (Show tab numbers in tab titles) for Vimperator. But it seems it is useless for VimFx.

**Comment by ghost** [comment]
I see. Thanks anyway.

Also, #90 is not useless for VimFX. In fact, I use it as a workaround for 'zF'. VimFx allows counters before movement commands, so '20K' moves you from the 5th to the 25th tab for instance. Your numbers save me the counting :) Only downside is that the numbers take some space from the tab title but I can live with that.

**Comment by idlewan** [comment]
Thanks for fixing that one! I was waiting for the release to end up on addons.mozilla.org to be able to test things out.
Works great!
