### ISSUE TITLE
"Hide the tab tree when there's only one tab" has no effect with "Show the tab tree in fullscreen"

### ISSUE THREAD

**Issue by imax9000** [traxium/tabtree#74]
When "Show the tab tree in fullscreen" option is checked "Hide the tab tree when there's only one tab" option has no effect, i.e. tab tree is still visible with just one tab in non-fullscreen window. I'd like the behaviour to be the same in both fullscreen and normal modes: if there's just one tab – don't show the tab tree.

Firefox 43.0.4, Mac OS X 10.11.2, Tab Tree 1.4.2

**Comment by traxium** [comment]
Fixed. Thanks to @tumpio. The fix will be available in the next version (1.4.3). Thank you for the bug report.
