### ISSUE TITLE
[Feature] - collapse and expand groups

### ISSUE THREAD

**Issue by jjeziorny** [traxium/tabtree#76]
It would be great if we could collapse and expand the groups like in the other tree style tabs addons (tab kit and treestyle tab).

Whilst it's awesome that the style on tabtree makes the tabs very slim and therefore you can fit more in the window, for some people with a LOT of tabs it would be grat to collaps them. Idealy also with an option to auto collapse/expand according to the selected group.

Thanks and great work btw, amazing addon!

**Comment by tumpio** [comment]
Duplicate of #4 , correct?

**Comment by jjeziorny** [comment]
Yes indeed it is. Sorry I ahven 't noticed that
