### ISSUE TITLE
Can't move tab between windows

### ISSUE THREAD

**Issue by iegor** [traxium/tabtree#79]
Hi,

I like this extension pretty much and want to use it.

Recently tried to move tab between two different windows and that failed.
What can be done ? Could you please point me to the place where you have moving routines, maybe I can help with fixing this ?

FF 39.0 Linux Gentoo x86_64 multilib

Regards,
Iegor

**Comment by tumpio** [comment]
Related and/or duplicates of #6 #39 #48

**Comment by iegor** [comment]
Oh.

tabstree version: 1.4.2

**Comment by iegor** [comment]
tumpio: Should I close this issue then ?

**Comment by tumpio** [comment]
I think so yes, but I would like to also hear answers to your questions.

**Comment by iegor** [comment]
I've commented on  #48 with same questions.

Will close this one now :)

Cheers
