### ISSUE TITLE
Audio indicator (Fx42.0) not present on tab.

### ISSUE THREAD

**Issue by kulmegil** [traxium/tabtree#8]
[Audio indicators](https://bugzilla.mozilla.org/show_bug.cgi?id=486262) targeting Firefox 42.0 release are missing on tabs created by Tab Tree.

**Comment by Boolean263** [comment]
I'm playing around with this. I've got basic functionality working with non-pinned tabs, now I'm trying to figure out how to make it work on pinned tabs. It may mean using something other than a toolbarbutton to represent pinned tabs, we'll have to see.

**Comment by Boolean263** [comment]
I've pushed my work to PR #51 for review. It's a doozy.

**Comment by traxium** [comment]
If nobody has anything to say I'll close the issue.
