### ISSUE TITLE
crashes linux user session 

### ISSUE THREAD

**Issue by ryzhikgagarin** [traxium/tabtree#83]
When trying to enable this addon it crashes a linux user session. 

TT 1.4.3
FF 44
ubuntu 14.04.03

**Comment by traxium** [comment]
Ubuntu 14.04 LTS in VirtualBox – no crashes. By the way, do you use Intel graphics card?

**Comment by ryzhikgagarin** [comment]
running on radeonHD.

upd. not actual. I have removed the addon and upgraded to wily.
