### ISSUE TITLE
TabTree removes custom entries from tab context menu

### ISSUE THREAD

**Issue by shockme** [traxium/tabtree#84]
Hi and thanks for a great addon!

I'm using an add-on named "Open with" that opens the page with a different browser (Chromium, Opera, etc). The "Open with" add-on adds menu entries to the tab context menu like "Open with Chromium Web Browser", but since installing TabTree those menu entries are missing.

I'm using TT 1.4.3 with FF 45.0b3 on Ubuntu 14.04.3

Thanks!

**Comment by traxium** [comment]
Fixed (at least with "Open with" add-on). Thanks for reporting the bug. The fix will be available in version 1.4.5.

**Comment by shockme** [comment]
Verified as fixed in v1.4.5

**Comment by shockme** [comment]
Thank you!
