### ISSUE TITLE
In shortcuts description, warn KDE users of possible unexpected effects for Ctrl-Alt-Shift-Pgup/Pgdn

### ISSUE THREAD

**Issue by meekreau** [traxium/tabtree#89]
Shortcuts Ctrl-Alt-Shift-Pgup/Pgdn collide with default shortcuts in KDE-based GNU/Linux distributions for 'Reboot without confirmation' / 'Power off without confirmation'. This is a weird decision of KDE designers to have this activated by default, but it would be nice to have a note on this fact in Tab Tree documentation too (e.g. on https://addons.mozilla.org/en-US/firefox/addon/tab-tree/) since shortcuts are not configurable in Tab Tree.

**Comment by traxium** [comment]
Done. I also created [description.en-us.htm](https://github.com/traxium/tabtree/blob/master/AMO/description.en-us.htm) — the add-on description from https://addons.mozilla.org/en-US/firefox/addon/tab-tree/ so feel free to edit it and send PR. Thank you for the suggestion.

**Comment by meekreau** [comment]
Thanks!
