### ISSUE TITLE
Show tab numbers in tab titles

### ISSUE THREAD

**Issue by meekreau** [traxium/tabtree#90]
The Vimperator plugin implements the tab numbering feature I dreamt of a lot. This allows to jump to a particular tab without using a mouse. Firefox, as far as I remember, allows to do this out of the box for tabs 1 to 9, but one should guess or count which number each tab has :) Vim-style plugins can do this for an arbitrary number of tabs.

In default tabs, the tab number is shown in the right upper corner of the tab title bar (Vimperator implementation). As this is clearly not shown in Tab Tree, would it be possible to have an option to prepend tab titles in Tab Tree with such a number that is independent of tab indentation?

**Comment by traxium** [comment]
Easy. I often used tab numbers for debugging. It's harder to attach these numbers to pinned tabs.

**Comment by tomdavey** [comment]
+1 -- great idea.

**Comment by traxium** [comment]
Done. I'll probably attach tab numbers to pinned tabs later. It's the 6th option from the top (or extensions.tabtree.tab-numbers).

**Comment by meekreau** [comment]
Awesome! Thanks a lot!

As I'm not an active user of pin tabs, I'm very happy even with the 'partial' implementation. Shall I close the issue or shall it remain open for keeping track of the 'pinned tab' option?

**Comment by traxium** [comment]
If you are satisfied close the issue. And if somebody wants numbers on pinned tabs very badly then he is free to reopen this issue or create a new one.

UPD: as it seems only openers or me can reopen closed issues.
