### ISSUE TITLE
[Feature Request] Open search bar in child tab

### ISSUE THREAD

**Issue by TempSpas** [traxium/tabtree#99]
I have **browser.search.openintab** set to true in about:config, which opens search queries in a new tab when using the search bar so I can quickly search for information related to the page I'm on without leaving it. The add-on currently opens these searches in a new parent tab, when ideally it should open in a child of the current tab.

**Comment by Fabiensk** [comment]
I had a look and unfortunately there is no obvious way to differentiate the cases where:
- the user used "browser.search.openintab"
- the user type an URL or search terms in the URL bar and pressed "alt-enter"
- the user pressed "control-T" to open a new tab

**Comment by TempSpas** [comment]
Ah, I see. I guess the current implementation is fair then; I've adjusted to it.
